services:
  server:
    build: .
    restart: unless-stopped
    command: -prod -db /app/data/rpb.db
    environment:
      - RPB_SECRET=${RPB_SECRET}
    ports:
      - 5000:5000
    volumes:
      - data:/app/data
    devices:
      - /dev/mem:/dev/mem
      - /dev/gpiomem:/dev/gpiomem
      - /proc/device-tree/soc/ranges:/proc/device-tree/soc/ranges

volumes:
  data: