services:
  rpb:
    build: .
    command: -prod
    environment:
      - RPB_SECRET=${RPB_SECRET}
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: /dev/mem
        target: /dev/mem
      - type: bind
        source: /dev/gpiomem
        target: /dev/gpiomem
      - type: bind
        source: /proc/device-tree/soc/ranges
        target: /proc/device-tree/soc/ranges
      - $(PWD)/rpb.db:/app/rpb.db